### ISSUE TITLE
Lunchbox 1.10.0 - CMake configuration fails in standalone build

### ISSUE THREAD

**Issue by seifertm** [Eyescale/Lunchbox#186]
I am trying to package Lunchbox for Gentoo Linux. Therefore, I do not follow the official build instructions using Buildyard, but call CMake through the package manager with Buildyard disabled.

While this procedure used to work with Lunchbox 1.9.1, the CMake build fails with 1.10.0. The relevant error should be the following:

    CMake Error at CMake/common/clangcheckTargets.cmake:42 (get_target_property):
      INTERFACE_LIBRARY targets may only have whitelisted properties.  The
      property "SOURCES" is not allowed.
    Call Stack (most recent call first):
      CMake/common/TargetHooks.cmake:36 (add_clangcheck)
      /usr/share/cmake/Modules/FindThreads.cmake:207 (add_library)
      pthreads/CMakeLists.txt:4 (find_package)
      CMakeLists.txt:64 (include)

The complete build log including the CMake call is available here:
https://gist.github.com/seifertm/932e6ff8205e9b4917e7

**Comment by eile** [comment]
Seems you are using cmake 3.1?

This has been fixed in Eyescale/CMake#275, although that change has another issue.

**Comment by eile** [comment]
We are testing Eyescale/CMake#276 right now, if it works you need the two files in the PR to build. Updating .gitexternals to the lasted HEAD might work too, although we did not keep track what changed since 1.10.

**Comment by seifertm** [comment]
Thanks for the fast reaction! Yes, I am using CMake 3.1.0.

Here is what I did:
I updated the .gitexternals file to fetch commit d3767a95e4ac87882b13c0a45d1bcfb96a329328 of the CMake project. The build then complained about Buildyard bootstrap support being removed, so I deleted the lines invoking Buildyard in CMakeLists.txt.
The full patch I applied to the 1.10.0 release can be found here:
https://gist.github.com/seifertm/27776cba8dfe430f8330

I am getting the same error, though. Note that my build errors out in `CMake/common/clangcheckTargets.cmake`. The two pull requests only changed `CppcheckTargets.cmake` and  `CpplintTargets.cmake`. (I have Clang installed, but GCC will be used for the build.)

Should we reopen or should I file an issue in  Eyescale/CMake instead?

**Comment by eile** [comment]
Can you try the head of the 1.10 branch? I merged the changes in there, but can't test due to lack of CMake 3.1.

**Comment by seifertm** [comment]
The 1.10 branch (commit dbc14e59d9de3be5a6c5d75e0a2be59e70f7210f) gives the same error in `CMake/common/clangcheckTargets.cmake:42`.

**Comment by seifertm** [comment]
The 1.10 branch configures and compiles fine now. Thanks!

**Comment by seifertm** [comment]
Gentoo users will now be able to install the git version of the 1.10 branch of Lunchbox:
https://bugs.gentoo.org/show_bug.cgi?id=541222
