### ISSUE TITLE
Package CMake modules in the release tar-ball

### ISSUE THREAD

**Issue by seifertm** [Eyescale/Lunchbox#187]
As I mentioned in a previous issue, I am currently trying to package Lunchbox for Gentoo Linux. While the standard build with Buildyard works nicely, I fear that a Lunchbox package cannot make it into the official package list of Gentoo (the Portage Tree), because the CMake build loads external dependencies during build time.

Loading the CMake modules through git causes two problems from my point of view:
- If the loaded CMake modules are not verified after the download, there is a risk that the build uses compromised CMake files, posing a potential security threat.
- There is no possibility to install the Lunchbox package without a running Internet connection

I don't know much about other distributions' packaging policies, but I imagine that they had similar concerns.

Is there a possibility that the CMake modules will be included in future releases?

**Comment by eile** [comment]
We have a flatten target which adds the git externals into the base repo. For some reason that hasn't happened for 1.10 - will do now.
