### ISSUE TITLE
Lunchbox does not compile in Buildyard, missing Servus

### ISSUE THREAD

**Issue by RubenGarcia** [Eyescale/Lunchbox#226]
On a clean ubuntu 14.04.
(where can Servus be found? It does not seem to be in https://github.com/Eyescale)

git clone https://github.com/Eyescale/Buildyard
cd Buildyard
cmake .
make
make Lunchbox
Can't build Lunchbox: missing Servus
make Servus
make[1]: *** No rule to make target `Servus'.  Stop.

**Comment by rdumusc** [comment]
Servus can be found here: https://github.com/HBPVIS/Servus/
Please note that building using Buildyard is no longer recommended and maintained, dependencies are downloaded and built using the git subproject feature. See: https://github.com/Eyescale/Lunchbox#building-building

**Comment by RubenGarcia** [comment]
Ah, good to know. Closing but then.
