### ISSUE TITLE
Build with latest Common CMake modules 

### ISSUE THREAD

**Issue by awissu** [Eyescale/Lunchbox#246]
124s] /home/abuild/rpmbuild/BUILD/Lunchbox-1.12.0/CMake/common/cpp/test.h:100:51: error: too many arguments to function 'void lunchbox::abort()'
[  124s]              lunchbox::abort( true /*dumpThreads*/ );
[  124s]                                                    ^
[  124s] In file included from /home/abuild/rpmbuild/BUILD/Lunchbox-1.12.0/lunchbox/thread.h:24:0,
[  124s]                  from /home/abuild/rpmbuild/BUILD/Lunchbox-1.12.0/CMake/common/cpp/test.h:34,
[  124s]                  from /home/abuild/rpmbuild/BUILD/Lunchbox-1.12.0/tests/any.cpp:18:
[  124s] /home/abuild/rpmbuild/BUILD/Lunchbox-1.12.0/lunchbox/debug.h:36:19: note: declared here
[  124s]  LUNCHBOX_API void abort();

See more: https://pmbs.links2linux.de/package/live_build_log/home:awissu:equalizer-qt5/Lunchbox/openSUSE_Tumbleweed/i586

**Comment by eile** [comment]
Hi - you should use https://github.com/Eyescale/CMake/tree/b158c68 to build Lunchbox 1.12, not master.

**Comment by eile** [comment]
We should actually create a release branch where we flatten the externals into the branch.

**Comment by eile** [comment]
Fixed in d22d2be. Please use 1.12 branch, or shall I make a 1.12.1 release?
