### ISSUE TITLE
skv::PersistentMap

### ISSUE THREAD

**Issue by lxq** [Eyescale/Lunchbox#268]
Does skv::PersistentMap not implement getValues() and takeValues ? Or, may I not use skv?

The errers are:

/home/lxq/eq/Equalizer/Lunchbox/lunchbox/persistentMap.cpp: In function ‘lunchbox::detail::PersistentMap* {anonymous}::_newImpl(const servus::URI&)’:
/home/lxq/eq/Equalizer/Lunchbox/lunchbox/persistentMap.cpp:73:54: error: invalid new-expression of abstract class type ‘lunchbox::skv::PersistentMap’
         return new lunchbox::skv::PersistentMap( uri );
                                                      ^
In file included from /home/lxq/eq/Equalizer/Lunchbox/lunchbox/persistentMap.cpp:56:0:
/home/lxq/eq/Equalizer/Lunchbox/lunchbox/skv/persistentMap.h:43:7: note:   because the following virtual functions are pure within ‘lunchbox::skv::PersistentMap’:
 class PersistentMap : public detail::PersistentMap
       ^
/home/lxq/eq/Equalizer/Lunchbox/lunchbox/persistentMap.cpp:38:18: note: 	virtual void lunchbox::detail::PersistentMap::getValues(const Strings&, const ConstValueFunc&) const
     virtual void **getValues**( const Strings& keys,
                  ^
/home/lxq/eq/Equalizer/Lunchbox/lunchbox/persistentMap.cpp:40:18: note: 	virtual void lunchbox::detail::PersistentMap::**takeValues**(const Strings&, const ValueFunc&) const
     virtual void takeValues( const Strings& keys,
                  ^
lunchbox/CMakeFiles/Lunchbox.dir/build.make:446: recipe for target 'lunchbox/CMakeFiles/Lunchbox.dir/persistentMap.cpp.o' failed
make[2]: *** [lunchbox/CMakeFiles/Lunchbox.dir/persistentMap.cpp.o] Error 1
CMakeFiles/Makefile2:3472: recipe for target 'lunchbox/CMakeFiles/Lunchbox.dir/all' failed
make[1]: *** [lunchbox/CMakeFiles/Lunchbox.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lxq** [comment]
Can someone give an idea for solve the question? 
Thanks!

**Comment by tribal-tec** [comment]
I haven't paid attention to skv-backend while implementing takeValues/getValues for leveldb. I have no setup to develop and test, hence not done. If you have an skv setup and a use case for it, feel free to provide an implementation.

**Comment by lxq** [comment]
Thanks for your answer. So, I remove the skv library. It works well.
